### PR TITLE
Allow setting overwriteWithBlank to false on edit contact requests

### LINKED ISSUE #37: `overwriteWithBlank` cannot be set to `false`
Hi David,

Thank you for maintaining and making available this package. It's very helpful.

We found that in some cases for the editing contact request `/PATCH /contacts/ID/edit` we would like to turn off the optional `overwiteWithBlank` parameter. Currently this is not supported with the `editContact` method because it is always set to `true` and overrides any supplied arguments, even if one explicitly sets `overwriteContact: false`. See line: https://github.com/vdavid/node-mautic/blob/643567e30c26faedad0dd8915b39032e33a37c0c/MauticConnector.js#L275

I tried to create a Pull request on a new feature branch but was unable to push that to the repo to submit the PR. Please let me know if there's anything I can do for that. Thanks !

### PR DESCRIPTION
**Pull request by wfulgenzi**
Close #37

### CODE REVIEW

**Comment by wfulgenzi** [comment]
Hey @vdavid sorry for the delay, I didn't get a notification on your reply ! Let me know if any changes needed, cheers.

**Comment by vdavid** [comment]
Thanks! :)

**Comment by wfulgenzi** [comment]
Anything else needed on my end for that? Otherwise good to merge :).

**Comment by vdavid** [comment]
Sorry, I was extremely slow on this one. Thanks for the nudge!

**Pull request merged**
